#!/bin/bash

# get this scripts directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "Creating symlinks from $DIR"

# get the users home that is running this script
USER_HOME=$(eval echo ~${SUDO_USER})

# Map files to their location
declare -A filemap

filemap[".vim"]=$USER_HOME
filemap[".vimrc"]=$USER_HOME
filemap[".bashrc"]=$USER_HOME
filemap[".vim"]=$USER_HOME
filemap["startup"]="/etc/systemd/system/"


# enable hidden files to be able to be found
shopt -s dotglob

for filepath in $DIR/*
do
#   echo $filepath
    filename=`basename $filepath`
#   echo $filename
    copypath=${filemap[$filename]}
#   echo $copypath
    if [ -n "$copypath" ]
    then
        echo "Symlinking $filename to $copypath"
        rm -r $copypath/$filename
        ln -s $filepath $copypath
    fi
done

# disable hidden files being picked up
shopt -u dotglob

